services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092" 
    environment:
      CLUSTER_ID: '4L62ydgTyN-G4OJgKmQgJw'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      #test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  # Init-контейнер для создания топика my-topic
  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    init: true
    depends_on:
      kafka:
        condition: service_healthy # Ждем, пока Kafka запустится и проверит готовность
    command: >
      /bin/bash -c "
        echo 'Ожидание готовности Kafka...' &&
        cub kafka-ready -b kafka:9092 1 20 &&
        echo 'Создание топика...' &&
        kafka-topics --create --if-not-exists --bootstrap-server localhost:9092 --topic test-topic --partitions 1 --replication-factor 1"

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: gophprofile_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gophprofiledb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: gophprofile_user
      MINIO_ROOT_PASSWORD: supersecretpassword
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped

  app:
    build: .
    container_name: gophprofile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URI=postgres://gophprofile_user:secret@postgres/gophprofiledb?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  pg_data:
  minio_data:
  kafka_data:
