# Глобальные настройки именования
nameOverride: ""
fullnameOverride: "goph-infra"

# Конфигурация PostgreSQL
postgres:
  enabled: true
  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent
  env:
    user: gophprofile_user
    password: secret
    db: gophprofiledb
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 500m
  persistence:
    size: 1Gi
    accessModes:
      - ReadWriteOnce
  service:
    port: 5432

# Конфигурация Kafka (KRaft mode)
kafka:
  enabled: true
  image:
    repository: confluentinc/cp-kafka
    tag: 8.0.7
    pullPolicy: IfNotPresent
  clusterId: 'MkU3OEVBNTcwNTJENDM2Qk'
  heapOpts: "-Xms1024m -Xmx1024m"
  resources:
    requests:
      memory: 1024Mi
      cpu: 1000m
    limits:
      memory: 2048Mi
      cpu: 2000m
  persistence:
    size: 2Gi
    accessModes:
      - ReadWriteOnce
  service:
    externalPort: 9092
    internalPort: 9093

# Конфигурация MinIO
minio:
  enabled: true
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2025-09-07T16-13-09Z
    pullPolicy: IfNotPresent
  env:
    rootUser: gophprofile_user
    rootPassword: supersecretpassword
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200m
  persistence:
    size: 5Gi
    accessModes:
      - ReadWriteOnce
  service:
    apiPort: 9000
    consolePort: 9001

# Настройки стека Observability
observability:
  enabled: true
  
  otelCollector:
    image: otel/opentelemetry-collector-contrib:0.143.0
    resources:
      requests: { memory: "128Mi", cpu: "200m" }
      limits: { memory: "256Mi", cpu: "400m" }
      
  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    resources:
      requests: { memory: "128Mi", cpu: "50m" }
      limits: { memory: "256Mi", cpu: "200m" }
      
  loki:
    image: grafana/loki:main-0fd55b9
    resources:
      requests: { memory: "128Mi", cpu: "50m" }
      limits: { memory: "256Mi", cpu: "200m" }
    persistence:
      size: 5Gi
      
  prometheus:
    image: prom/prometheus:v3.13.2
    resources:
      requests: { memory: "128Mi", cpu: "50m" }
      limits: { memory: "256Mi", cpu: "200m" }
    persistence:
      size: 5Gi
      
  grafana:
    image: grafana/grafana:13.1
    adminUser: admin
    adminPassword: admin
    resources:
      requests: { memory: "256Mi", cpu: "100m" }
      limits: { memory: "512Mi", cpu: "400m" }
    persistence:
      size: 1Gi
      
  nodeExporter:
    image: prom/node-exporter:v1.12.1
    resources:
      requests: { memory: "32Mi", cpu: "10m" }
      limits: { memory: "64Mi", cpu: "50m" }

app:
  enabled: true
  replicas: 1
  image:
    repository: gophprofile-app
    tag: 12.0.1                  
    pullPolicy: Never            
  service:
    port: 8080
    nodePort: 32080              
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
