{{- if .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gophprofile.fullname" . }}-app-server
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    component: app-server
spec:
  #replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "gophprofile.selectorLabels" . | nindent 6 }}
      component: app-server
  template:
    metadata:
      labels:
        {{- include "gophprofile.selectorLabels" . | nindent 8 }}
        component: app-server
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: wait-for-dependencies
        image: alpine:3.18
        command:
        - sh
        - -c
        - |
          echo "Ожидание запуска инфраструктуры..."
          
          until nc -z -w 2 {{ include "gophprofile.fullname" . }}-postgres 5432; do
            echo "Ожидание PostgreSQL (5432)..."
            sleep 2
          done
          
          until nc -z -w 2 {{ include "gophprofile.fullname" . }}-minio {{ .Values.minio.service.apiPort }}; do
            echo "Ожидание MinIO ({{ .Values.minio.service.apiPort }})..."
            sleep 2
          done
          
          until nc -z -w 2 {{ include "gophprofile.fullname" . }}-kafka {{ .Values.kafka.service.internalPort }}; do
            echo "Ожидание Kafka ({{ .Values.kafka.service.internalPort }})..."
            sleep 2
          done
          
          echo "Вся инфраструктура готова к работе!"
      containers:
      - name: api-server
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        command: ["./gophprofile"]
        ports:
        - containerPort: {{ .Values.app.service.port }}
          name: http
        env:
        - name: SERVER_PORT
          value: ":{{ .Values.app.service.port }}"
        - name: DB_PASSWORD_RAW
          valueFrom:
            secretKeyRef:
              name: {{ include "gophprofile.fullname" . }}-secrets
              key: postgres-password
        - name: DATABASE_URI
          value: "postgres://{{ .Values.postgres.env.user }}:$(DB_PASSWORD_RAW)@{{ include "gophprofile.fullname" . }}-postgres:5432/{{ .Values.postgres.env.db }}?sslmode=disable"
        - name: MINIO_HOST
          value: "{{ include "gophprofile.fullname" . }}-minio:{{ .Values.minio.service.apiPort }}"
        - name: MINIO_ROOT_USER
          value: {{ .Values.minio.env.rootUser | quote }}
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "gophprofile.fullname" . }}-secrets
              key: minio-secret-key
        - name: MINIO_SSL
          value: "false"
        - name: KAFKA_BROKERS
          value: "{{ include "gophprofile.fullname" . }}-kafka:{{ .Values.kafka.service.internalPort }}"
        - name: MIGRATIONS_PATH
          value: "file://migrations"
        - name: OTEL_SERVICE_NAME
          value: "gophprofileservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=development"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://{{ include "gophprofile.fullname" . }}-otel-collector:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        resources:
          {{- toYaml .Values.app.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.fullname" . }}-app-server
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    component: app-server
spec:
  type: ClusterIP
  selector:
    {{- include "gophprofile.selectorLabels" . | nindent 4 }}
    component: app-server
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.port }}
    # nodePort: {{ .Values.app.service.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gophprofile.fullname" . }}-worker
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    component: worker
spec:
  #replicas: 1
  selector:
    matchLabels:
      {{- include "gophprofile.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{- include "gophprofile.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      terminationGracePeriodSeconds: 45
      initContainers:
      - name: wait-for-dependencies
        image: alpine:3.18
        command:
        - sh
        - -c
        - |
          echo "Ожидание запуска инфраструктуры..."
          
          until nc -z -w 2 {{ include "gophprofile.fullname" . }}-postgres 5432; do
            echo "Ожидание PostgreSQL (5432)..."
            sleep 2
          done
          
          until nc -z -w 2 {{ include "gophprofile.fullname" . }}-minio {{ .Values.minio.service.apiPort }}; do
            echo "Ожидание MinIO ({{ .Values.minio.service.apiPort }})..."
            sleep 2
          done
          
          until nc -z -w 2 {{ include "gophprofile.fullname" . }}-kafka {{ .Values.kafka.service.internalPort }}; do
            echo "Ожидание Kafka ({{ .Values.kafka.service.internalPort }})..."
            sleep 2
          done
          
          echo "Вся инфраструктура готова к работе!"
      containers:
      - name: worker
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        command: ["./worker"]
        env:
        - name: SERVER_PORT
          value: ":{{ .Values.app.service.port }}"
        - name: DB_PASSWORD_RAW
          valueFrom:
            secretKeyRef:
              name: {{ include "gophprofile.fullname" . }}-secrets
              key: postgres-password
        - name: DATABASE_URI
          value: "postgres://{{ .Values.postgres.env.user }}:$(DB_PASSWORD_RAW)@{{ include "gophprofile.fullname" . }}-postgres:5432/{{ .Values.postgres.env.db }}?sslmode=disable"
        - name: MINIO_HOST
          value: "{{ include "gophprofile.fullname" . }}-minio:{{ .Values.minio.service.apiPort }}"
        - name: MINIO_ROOT_USER
          value: {{ .Values.minio.env.rootUser | quote }}
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "gophprofile.fullname" . }}-secrets
              key: minio-secret-key
        - name: MINIO_SSL
          value: "false"
        - name: KAFKA_BROKERS
          value: "{{ include "gophprofile.fullname" . }}-kafka:{{ .Values.kafka.service.internalPort }}"
        - name: MIGRATIONS_PATH
          value: "file://migrations"
        - name: OTEL_SERVICE_NAME
          value: "gophprofileservice-worker"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=development"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://{{ include "gophprofile.fullname" . }}-otel-collector:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        resources:
          {{- toYaml .Values.app.workerResources | nindent 10 }}
{{- end }}
