apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gophprofile.fullname" . }}-postgres-policy
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gophprofile.selectorLabels" . | nindent 6 }}
      component: postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          component: app-server
    - podSelector:
        matchLabels:
          component: worker
    ports:
    - protocol: TCP
      port: 5432
