apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
data:
  # Извлекаем пароли из отдельного файла и кодируем в base64
  postgres-password: {{ .Values.secrets.postgresPassword | required "secrets.postgresPassword must be provided in values-secrets.yaml!" | b64enc | quote }}
  minio-secret-key: {{ .Values.secrets.minioRootPassword | required "secrets.minioRootPassword must be provided in values-secrets.yaml!" | b64enc | quote }}
  grafana-admin-password: {{ .Values.secrets.grafanaAdminPassword | required "secrets.grafanaAdminPassword must be provided in values-secrets.yaml!" | b64enc | quote }}