{{- if .Values.observability.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gophprofile-infra.fullname" . }}-ingress
  namespace: infra
spec:
  ingressClassName: nginx # Связывает домены с деплойментом, который мы описали на Шаге 1
  rules:
  - host: grafana.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "gophprofile-infra.fullname" . }}-grafana
            port:
              number: 3000
  - host: jaeger.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "gophprofile-infra.fullname" . }}-jaeger
            port:
              number: 16686
{{- end }}
