apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
    spec:
      hostNetwork: true # Позволит контроллеру слушать порты 80/443 прямо на вашем сервере devsrv
      containers:
      - name: controller
        # Используем альтернативный стабильный образ, который часто кэшируется или доступен без вебхуков
        image: mirror.gcr.io/google-containers/nginx-ingress-controller:v1.11.1
        args:
        - /nginx-ingress-controller
        - --election-id=ingress-nginx-leader
        - --controller-class=k8s.io/ingress-nginx
        - --ingress-class=nginx
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
        - containerPort: 443
          hostPort: 443
          name: https
        resources:
          requests: { cpu: "100m", memory: "90Mi" }
          limits: { cpu: "500m", memory: "256Mi" }
