{{- if .Values.observability.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gophprofile-infra.fullname" . }}-otel-config
  labels:
    {{- include "gophprofile-infra.labels" . | nindent 4 }}
data:
  otel-collector-config.yml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
      resource/add-job:
        attributes:
          - key: job
            from_attribute: service.name
            action: upsert
    exporters:
      prometheus:
        endpoint: '0.0.0.0:8889'
        namespace: "gophprofile"
      otlphttp/loki:
        endpoint: http://{{ include "gophprofile-infra.fullname" . }}-loki:3100/otlp
        compression: "gzip"
        tls:
          insecure: true
      otlp/jaeger:
        endpoint: "{{ include "gophprofile-infra.fullname" . }}-jaeger:4317"
        tls:
          insecure: true
    service:
      extensions: [health_check]
      pipelines:
        logs:
          receivers: [otlp]
          processors: [resource/add-job, batch]
          exporters: [otlphttp/loki]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gophprofile-infra.fullname" . }}-otel-collector
  labels:
    {{- include "gophprofile-infra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gophprofile-infra.selectorLabels" . | nindent 6 }}
      component: otel-collector
  template:
    metadata:
      labels:
        {{- include "gophprofile-infra.selectorLabels" . | nindent 8 }}
        component: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: "{{ .Values.observability.otelCollector.image }}"
        args: ["--config=/etc/otel-collector-config.yml"]
        ports:
        - containerPort: 4317
          name: grpc
        - containerPort: 8889
          name: metrics
        resources:
          {{- toYaml .Values.observability.otelCollector.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/otel-collector-config.yml
          subPath: otel-collector-config.yml
      volumes:
      - name: config
        configMap:
          name: {{ include "gophprofile-infra.fullname" . }}-otel-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile-infra.fullname" . }}-otel-collector
spec:
  selector:
    {{- include "gophprofile-infra.selectorLabels" . | nindent 4 }}
    component: otel-collector
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317
  - name: metrics
    port: 8889
    targetPort: 8889
{{- end }}
